/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.utn.dsi.Pantallas;

import java.awt.Color;
import java.awt.Point;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.InputVerifier;
import javax.swing.JComponent;
import javax.swing.JFormattedTextField;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author juani
 */
public class Pantalla extends javax.swing.JFrame {

    private Gestor g;
    private DefaultListModel categorias_model = new DefaultListModel();
    private DefaultListModel categorias_seleccionadas_model = new DefaultListModel();
    private DefaultListModel zonas_model = new DefaultListModel();
    private DefaultListModel zonas_seleccionadas_model = new DefaultListModel();
    private DefaultComboBoxModel metodos_model = new DefaultComboBoxModel();

    /**
     * Creates new form Pantalla
     */
    public Pantalla() { // Nota: Seria opcionEstadisticaConsumo();
        initComponents();
        this.titulo.setLocation(12, 12);
        this.setSize(this.titulo.getSize().width + 24, this.titulo.getSize().height + this.fecha_panel.getSize().height);
        this.categorias_no_list.setModel(categorias_model);
        this.categorias_incluidas_list.setModel(categorias_seleccionadas_model);
        this.zonas_no_list.setModel(zonas_model);
        this.zonas_incluidas_list.setModel(zonas_seleccionadas_model);
        this.metodo_combo.setModel(metodos_model);
        this.fecha_desde_field.setInputVerifier(new DateVerifier());
        this.fecha_hasta_field.setInputVerifier(new DateVerifier());

        this.habilitarVentana();
        g = new Gestor(this);
        g.estadisticaConsumo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        titulo = new javax.swing.JLabel();
        layoutPanel = new javax.swing.JPanel();
        fecha_panel = new javax.swing.JPanel();
        fecha_desde_field = new javax.swing.JFormattedTextField();
        fecha_hasta_field = new javax.swing.JFormattedTextField();
        btnConfirmarPeriodo = new javax.swing.JButton();
        zonas_panel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        zonas_no_list = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        zonas_incluidas_list = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnConfirmarZonas = new javax.swing.JButton();
        btnEliminarZonas = new javax.swing.JButton();
        btnAddZonas = new javax.swing.JButton();
        categorias_panel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        categorias_no_list = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        categorias_incluidas_list = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnConfirmarCategorias = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        metodo_panel = new javax.swing.JPanel();
        metodo_combo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        btnConfirmarMetodo = new javax.swing.JButton();
        confirmacion_panel = new javax.swing.JPanel();
        confirmar_button = new javax.swing.JButton();
        reporte_panel = new javax.swing.JPanel();
        titulo_zonas = new javax.swing.JLabel();
        titulo_categorias = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        reporte_zonas = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        reporte_categorias = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Estadística de Consumos");
        setEnabled(false);
        setMinimumSize(new java.awt.Dimension(20, 450));
        setName("pantalla_form"); // NOI18N

        titulo.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Estadística de Consumos");
        titulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        titulo.setMaximumSize(new java.awt.Dimension(440, 43));
        titulo.setMinimumSize(new java.awt.Dimension(440, 43));
        titulo.setName(""); // NOI18N
        titulo.setPreferredSize(new java.awt.Dimension(440, 43));
        titulo.setRequestFocusEnabled(false);

        layoutPanel.setMaximumSize(new java.awt.Dimension(1200, 800));
        layoutPanel.setLayout(new javax.swing.OverlayLayout(layoutPanel));

        fecha_panel.setMaximumSize(layoutPanel.getMaximumSize());

        fecha_desde_field.setText("Desde (dd/mm/aaaa)");
        fecha_desde_field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fecha_desde_fieldFocusGained(evt);
            }
        });

        fecha_hasta_field.setText("Hasta (dd/mm/aaaa)");
        fecha_hasta_field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fecha_hasta_fieldFocusGained(evt);
            }
        });
        fecha_hasta_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fecha_hasta_fieldActionPerformed(evt);
            }
        });

        btnConfirmarPeriodo.setText("Siguiente");
        btnConfirmarPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarPeriodoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fecha_panelLayout = new javax.swing.GroupLayout(fecha_panel);
        fecha_panel.setLayout(fecha_panelLayout);
        fecha_panelLayout.setHorizontalGroup(
            fecha_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fecha_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fecha_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fecha_panelLayout.createSequentialGroup()
                        .addComponent(fecha_desde_field, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fecha_hasta_field, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnConfirmarPeriodo, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        fecha_panelLayout.setVerticalGroup(
            fecha_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fecha_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fecha_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fecha_desde_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fecha_hasta_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 266, Short.MAX_VALUE)
                .addComponent(btnConfirmarPeriodo)
                .addGap(12, 12, 12))
        );

        layoutPanel.add(fecha_panel);

        zonas_panel.setMaximumSize(layoutPanel.getMaximumSize());

        jScrollPane3.setPreferredSize(new java.awt.Dimension(200, 200));

        zonas_no_list.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        zonas_no_list.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        zonas_no_list.setMinimumSize(new java.awt.Dimension(61, 200));
        jScrollPane3.setViewportView(zonas_no_list);

        jScrollPane4.setPreferredSize(new java.awt.Dimension(200, 200));

        zonas_incluidas_list.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        zonas_incluidas_list.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        jScrollPane4.setViewportView(zonas_incluidas_list);

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Zonas");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Incluidas");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("No incluidas");

        btnConfirmarZonas.setText("Siguiente");
        btnConfirmarZonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarZonasActionPerformed(evt);
            }
        });

        btnEliminarZonas.setText("Eliminar");
        btnEliminarZonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarZonasActionPerformed(evt);
            }
        });

        btnAddZonas.setText("Agregar");
        btnAddZonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddZonasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout zonas_panelLayout = new javax.swing.GroupLayout(zonas_panel);
        zonas_panel.setLayout(zonas_panelLayout);
        zonas_panelLayout.setHorizontalGroup(
            zonas_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(zonas_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(zonas_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnConfirmarZonas, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(zonas_panelLayout.createSequentialGroup()
                        .addGroup(zonas_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAddZonas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(zonas_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEliminarZonas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(zonas_panelLayout.createSequentialGroup()
                                .addGroup(zonas_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        zonas_panelLayout.setVerticalGroup(
            zonas_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(zonas_panelLayout.createSequentialGroup()
                .addGroup(zonas_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(zonas_panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5))
                    .addGroup(zonas_panelLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(zonas_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))))
                .addGap(0, 0, 0)
                .addGroup(zonas_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(zonas_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddZonas, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarZonas, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnConfirmarZonas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layoutPanel.add(zonas_panel);

        categorias_panel.setMaximumSize(layoutPanel.getMaximumSize());

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(200, 200));

        categorias_no_list.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        categorias_no_list.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        categorias_no_list.setMaximumSize(new java.awt.Dimension(200, 200));
        categorias_no_list.setMinimumSize(new java.awt.Dimension(200, 200));
        categorias_no_list.setPreferredSize(new java.awt.Dimension(200, 200));
        jScrollPane1.setViewportView(categorias_no_list);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setPreferredSize(new java.awt.Dimension(200, 200));

        categorias_incluidas_list.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        categorias_incluidas_list.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        categorias_incluidas_list.setMaximumSize(new java.awt.Dimension(61, 200));
        jScrollPane2.setViewportView(categorias_incluidas_list);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Categorias");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Incluidas");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("No incluidas");

        btnConfirmarCategorias.setLabel("Siguiente");
        btnConfirmarCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarCategoriasActionPerformed(evt);
            }
        });

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout categorias_panelLayout = new javax.swing.GroupLayout(categorias_panel);
        categorias_panel.setLayout(categorias_panelLayout);
        categorias_panelLayout.setHorizontalGroup(
            categorias_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(categorias_panelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(categorias_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, categorias_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnConfirmarCategorias)
                        .addGroup(categorias_panelLayout.createSequentialGroup()
                            .addGroup(categorias_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(12, 12, 12)
                            .addGroup(categorias_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnEliminar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(12, 12, 12))
        );
        categorias_panelLayout.setVerticalGroup(
            categorias_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(categorias_panelLayout.createSequentialGroup()
                .addGroup(categorias_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(categorias_panelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1))
                    .addGroup(categorias_panelLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(categorias_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(categorias_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(categorias_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnConfirmarCategorias)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layoutPanel.add(categorias_panel);

        metodo_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Método Estadístico");

        btnConfirmarMetodo.setText("Siguiente");
        btnConfirmarMetodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarMetodoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout metodo_panelLayout = new javax.swing.GroupLayout(metodo_panel);
        metodo_panel.setLayout(metodo_panelLayout);
        metodo_panelLayout.setHorizontalGroup(
            metodo_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(metodo_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(metodo_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(metodo_panelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(metodo_combo, 0, 1, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, metodo_panelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnConfirmarMetodo)))
                .addContainerGap())
        );
        metodo_panelLayout.setVerticalGroup(
            metodo_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(metodo_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(metodo_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(metodo_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnConfirmarMetodo)
                .addContainerGap())
        );

        layoutPanel.add(metodo_panel);

        confirmacion_panel.setMaximumSize(layoutPanel.getMaximumSize());
        confirmacion_panel.setLayout(new java.awt.GridBagLayout());

        confirmar_button.setText("Confirmar");
        confirmar_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmar_buttonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(49, 96, 73, 123);
        confirmacion_panel.add(confirmar_button, gridBagConstraints);

        layoutPanel.add(confirmacion_panel);

        reporte_panel.setMaximumSize(layoutPanel.getMaximumSize());

        titulo_zonas.setText("Zonas");

        titulo_categorias.setText("Categorias");

        jScrollPane5.setEnabled(false);

        reporte_zonas.setEditable(false);
        reporte_zonas.setColumns(20);
        reporte_zonas.setRows(5);
        jScrollPane5.setViewportView(reporte_zonas);

        jScrollPane6.setEnabled(false);

        reporte_categorias.setEditable(false);
        reporte_categorias.setColumns(20);
        reporte_categorias.setRows(5);
        jScrollPane6.setViewportView(reporte_categorias);

        javax.swing.GroupLayout reporte_panelLayout = new javax.swing.GroupLayout(reporte_panel);
        reporte_panel.setLayout(reporte_panelLayout);
        reporte_panelLayout.setHorizontalGroup(
            reporte_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reporte_panelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(reporte_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(reporte_panelLayout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(reporte_panelLayout.createSequentialGroup()
                        .addComponent(titulo_zonas)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(reporte_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(reporte_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titulo_categorias)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );
        reporte_panelLayout.setVerticalGroup(
            reporte_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reporte_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo_zonas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(titulo_categorias)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layoutPanel.add(reporte_panel);

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(layoutPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jButton1)))
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(layoutPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jButton1)
                .addGap(12, 12, 12))
        );

        getAccessibleContext().setAccessibleName("Estadistica de Consumos");
        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fecha_hasta_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fecha_hasta_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fecha_hasta_fieldActionPerformed

    private void btnConfirmarPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarPeriodoActionPerformed
        tomarPeriodo();
    }//GEN-LAST:event_btnConfirmarPeriodoActionPerformed

    private void btnConfirmarCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarCategoriasActionPerformed
        tomarSeleccionCategorias();
    }//GEN-LAST:event_btnConfirmarCategoriasActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        this.categorias_incluidas_list.setBackground(Color.WHITE);
        move_selected_items(this.categorias_no_list,
                this.categorias_incluidas_list);
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        move_selected_items(this.categorias_incluidas_list,
                this.categorias_no_list);
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnConfirmarZonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarZonasActionPerformed
        tomarSeleccionZonas();
    }//GEN-LAST:event_btnConfirmarZonasActionPerformed

    private void btnEliminarZonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarZonasActionPerformed
        move_selected_items(this.zonas_incluidas_list,
                this.zonas_no_list);
    }//GEN-LAST:event_btnEliminarZonasActionPerformed

    private void btnAddZonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddZonasActionPerformed
        this.zonas_incluidas_list.setBackground(Color.WHITE);
        move_selected_items(this.zonas_no_list,
                this.zonas_incluidas_list);
    }//GEN-LAST:event_btnAddZonasActionPerformed

    private void btnConfirmarMetodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarMetodoActionPerformed
        tomarSeleccionMetodoEstadistico();
    }//GEN-LAST:event_btnConfirmarMetodoActionPerformed

    private void confirmar_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmar_buttonActionPerformed
        tomarConfirmacion();
    }//GEN-LAST:event_confirmar_buttonActionPerformed

    private void fecha_desde_fieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fecha_desde_fieldFocusGained
        this.fecha_desde_field.selectAll();
    }//GEN-LAST:event_fecha_desde_fieldFocusGained

    private void fecha_hasta_fieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fecha_hasta_fieldFocusGained
        this.fecha_hasta_field.selectAll();
    }//GEN-LAST:event_fecha_hasta_fieldFocusGained

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        g.cancelar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void move_selected_items(JList from, JList into) {
        int[] indexes = from.getSelectedIndices();
        if (indexes.length == 0) {
            // TODO: Informar error, debe seleccionar al menos 1 categoria.
            return;
        }
        Object[] elementos = new Object[indexes.length + 1];
        DefaultListModel from_model = (DefaultListModel) from.getModel();
        DefaultListModel into_model = (DefaultListModel) into.getModel();
        for (int i = 0; i < indexes.length; i++) {
            elementos[i] = from_model.get(indexes[i]);
        }
        for (Object o : elementos) {

            into_model.addElement(o);
            from_model.removeElement(o);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pantalla();
            }
        });
    }

    public void opcionEstadisticaConsumos() {

    }

    public void habilitarVentana() {
        this.setEnabled(true);
        categorias_panel.setVisible(false);        
        zonas_panel.setVisible(false);
        metodo_panel.setVisible(false);
        confirmacion_panel.setVisible(false);
        reporte_panel.setVisible(false);
        this.setVisible(true);
    }

    public void solicitarPeriodo() {
        fecha_desde_field.setText("Desde (dd/mm/aaaa)");
        fecha_hasta_field.setText("Hasta (dd/mm/aaaa)");
        this.fecha_panel.setVisible(true);
    }

    public void tomarPeriodo() {
        DateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        Date desde, hasta;
        try {
            desde = df.parse(fecha_desde_field.getText());
            hasta = df.parse(fecha_hasta_field.getText());
        } catch (ParseException pe) {
            JOptionPane.showMessageDialog(null, "Error, fechas mal ingresadas.");
            return;
        }

        this.fecha_panel.setVisible(false);
        // TODO: Si el gestor indica que el periodo es invalido que se hace?
        g.tomarPeriodo(desde, hasta);
    }

    public void solicitarSeleccionCategorias(List categorias) {
        categorias_model.removeAllElements();
        categorias_seleccionadas_model.removeAllElements();

        for (Object categoria : categorias) {
            categorias_seleccionadas_model.addElement(categoria);
        }
        
        this.categorias_panel.setVisible(true);
    }

    public void tomarSeleccionCategorias() {
        if(categorias_seleccionadas_model.isEmpty()){
            this.categorias_incluidas_list.setBackground(Color.RED);
            return;
        }
        
        Object[] categorias = new Object[categorias_seleccionadas_model.getSize()];
        
        categorias_seleccionadas_model.copyInto(categorias);
        this.categorias_panel.setVisible(false);        
        g.tomarSeleccionCategorias(categorias);       
    }

    public void solicitarSeleccionZonas(List zonas) {
        zonas_model.removeAllElements();
        zonas_seleccionadas_model.removeAllElements();

        for (Object zona : zonas) {
            zonas_seleccionadas_model.addElement(zona);
        }      

        this.zonas_panel.setVisible(true);
    }

    public void tomarSeleccionZonas() {
        if(zonas_seleccionadas_model.isEmpty()){
            this.zonas_incluidas_list.setBackground(Color.RED);
            return;
        }
        Object[] zonas = new Object[zonas_seleccionadas_model.getSize()];
        zonas_seleccionadas_model.copyInto(zonas);
        this.zonas_panel.setVisible(false);
        g.tomarSeleccionZonas(zonas);        
    }

    public void solicitarSeleccionMetodoEstadistico(List metodos) {
        metodos_model.removeAllElements();
        for (Object metodo : metodos) {
            metodos_model.addElement(metodo);
        }
        this.metodo_panel.setVisible(true);
    }

    public void tomarSeleccionMetodoEstadistico() {
        Object metodo = this.metodo_combo.getSelectedItem();
        this.metodo_panel.setVisible(false);
        g.tomarSeleccionMetodoEstadistico(metodo);
    }

    public void solicitarConfirmacion() {
        this.confirmacion_panel.setVisible(true);
    }

    public void tomarConfirmacion() {
        this.confirmacion_panel.setVisible(false);
        g.tomarConfirmacion();
    }

    public void mostrarReporteZonas(String reporte) {
        this.reporte_zonas.setText(reporte);
        this.reporte_panel.setVisible(true);
    }
    
    public void mostrarReporteCategorias(String reporte){
        this.reporte_categorias.setText(reporte);
        this.reporte_panel.setVisible(true);
    }

    public void solicitarDecisionImpresion() {
        int ans = JOptionPane.showConfirmDialog(this, "¿Desea Imprimir el Informe?", 
                "Impresión", JOptionPane.YES_NO_OPTION);
        tomarDecisionImpresion(ans == 0);        
    }

    public void tomarDecisionImpresion(boolean print) {
        g.tomarDecisionImpresion(print);
    }

    private class DateVerifier extends InputVerifier {

        @Override
        public boolean verify(JComponent input) {
            JFormattedTextField tf = (JFormattedTextField) input;
            DateFormat df = new SimpleDateFormat("dd/MM/yyyy");
            try {
                Date cast = df.parse(tf.getText());
            } catch (ParseException pe) {
                tf.setBackground(Color.red);
                return false;
            }
            tf.setBackground(Color.white);
            return true;
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddZonas;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnConfirmarCategorias;
    private javax.swing.JButton btnConfirmarMetodo;
    private javax.swing.JButton btnConfirmarPeriodo;
    private javax.swing.JButton btnConfirmarZonas;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEliminarZonas;
    private javax.swing.JList<String> categorias_incluidas_list;
    private javax.swing.JList<String> categorias_no_list;
    private javax.swing.JPanel categorias_panel;
    private javax.swing.JPanel confirmacion_panel;
    private javax.swing.JButton confirmar_button;
    private javax.swing.JFormattedTextField fecha_desde_field;
    private javax.swing.JFormattedTextField fecha_hasta_field;
    private javax.swing.JPanel fecha_panel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JPanel layoutPanel;
    private javax.swing.JComboBox<String> metodo_combo;
    private javax.swing.JPanel metodo_panel;
    private javax.swing.JTextArea reporte_categorias;
    private javax.swing.JPanel reporte_panel;
    private javax.swing.JTextArea reporte_zonas;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel titulo_categorias;
    private javax.swing.JLabel titulo_zonas;
    private javax.swing.JList<String> zonas_incluidas_list;
    private javax.swing.JList<String> zonas_no_list;
    private javax.swing.JPanel zonas_panel;
    // End of variables declaration//GEN-END:variables
}
